### ISSUE TITLE
boost/make_unique.hpp not found

### ISSUE THREAD

**Issue by 1stl0ve** [plast-lab/cclyzer#6]
I'm getting an error when I'm trying to make cclyzer. I have installed the boost libraries, but I'm still receiving the following error when I run `make`:

```
src/DebugInfoProcessor.cpp:1:33: fatal error: boost/make_unique.hpp: No such file or directory
 #include <boost/make_unique.hpp>
```

Any suggestions?

Thanks.

**Comment by gbalats** [comment]
What distro are you running? Have you installed the `boost-dev` libraries (since the latter is what provides the boost header files)?

**Comment by 1stl0ve** [comment]
I'm running on Ubuntu 14.04 and I installed the `boost-dev` libraries.

**Comment by gbalats** [comment]
The `make_unique` function was introduced at [Boost 1.56](http://www.boost.org/doc/libs/1_56_0/libs/smart_ptr/make_unique.html). So, I assume you have an older version of boost installed. Can you try upgrading it?

**Comment by 1stl0ve** [comment]
I was using boost 1.55. I installed a newer version of boost, which got rid of that error. Now I'm running into problems compiling `tools/fact-generator/include/predicate.hpp`. It says that there are a number of references (i.e. `cclyzer:;Registry<cclyzer::EntityPredicate>::all()`) that are undefined.

**Comment by gbalats** [comment]
I've managed to reproduce the error on Ubuntu 14.04 via docker. This has to do with some explicit instantiations of class `cclyzer::Registry` failing to generate their respective `all()` static methods. I'll provide a fix shortly.

**Comment by gbalats** [comment]
It now compiles cleanly with Ubuntu 14.04 even without Boost 1.56. Please verify that the fix works for you.
